---
# handlers file for fail2ban

- name: start fail2ban
  systemd:
    name: fail2ban
    state: started
    enabled: yes

- name: restart fail2ban
  systemd:
    name: fail2ban
    state: restarted
